const clientsData = require('./data')
const Sequelize = require('sequelize')
// const db = new Sequelize('mysql://root:1234@localhost/crm_project')
const db = new Sequelize('mysql://bf7de9fd81a34a:1d8826be@eu-cdbr-west-03.cleardb.net/heroku_026d942682a000c?reconnect=true')
const dateFormat = require('dateformat')

const countryList = [
	"Afghanistan",
	"Albania",
	"Algeria",
	"American Samoa",
	"Andorra",
	"Angola",
	"Anguilla",
	"Antarctica",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Aruba",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bermuda",
	"Bhutan",
	"Bolivia",
	"Bonaire, Sint Eustatius and Saba",
	"Bosnia and Herzegovina",
	"Botswana",
	"Bouvet Island",
	"Brazil",
	"British Indian Ocean Territory",
	"Brunei Darussalam",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Cayman Islands",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Christmas Island",
	"Cocos Islands",
	"Colombia",
	"Comoros",
	"Congo",
	"Congo",
	"Cook Islands",
	"Costa Rica",
	"Croatia",
	"Cuba",
	"Curaçao",
	"Cyprus",
	"Czechia",
	"Côte d'Ivoire",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"Falkland Islands",
	"Faroe Islands",
	"Fiji",
	"Finland",
	"France",
	"French Guiana",
	"French Polynesia",
	"French Southern Territories",
	"Gabon",
	"Gambia",
	"Georgia",
	"Germany",
	"Ghana",
	"Gibraltar",
	"Greece",
	"Greenland",
	"Grenada",
	"Guadeloupe",
	"Guam",
	"Guatemala",
	"Guernsey",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Heard Island and McDonald Islands",
	"Holy See",
	"Honduras",
	"Hong Kong",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran",
	"Iraq",
	"Ireland",
	"Isle of Man",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jersey",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Korea",
	"Kuwait",
	"Kyrgyzstan",
	"Lao People's Democratic Republic",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macao",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Martinique",
	"Mauritania",
	"Mauritius",
	"Mayotte",
	"Mexico",
	"Micronesia",
	"Moldova",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Montserrat",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands",
	"New Caledonia",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"Niue",
	"Norfolk Island",
	"Northern Mariana Islands",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Pitcairn",
	"Poland",
	"Portugal",
	"Puerto Rico",
	"Qatar",
	"Republic of North Macedonia",
	"Romania",
	"Russian Federation",
	"Rwanda",
	"Réunion",
	"Saint Barthélemy",
	"Saint Helena, Ascension and Tristan da Cunha",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Martin (French part]",
	"Saint Pierre and Miquelon",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Sint Maarten (Dutch part)",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Georgia and the South Sandwich Islands",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan",
	"Suriname",
	"Svalbard and Jan Mayen",
	"Sweden",
	"Switzerland",
	"Syrian Arab Republic",
	"Taiwan",
	"Tajikistan",
	"Tanzania",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tokelau",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Turks and Caicos Islands",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates (UAE)",
	"United Kingdom of Great Britain and Northern Ireland",
	"United States of America (USA)",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Venezuela",
	"Viet Nam",
	"Virgin Islands (British)",
	"Virgin Islands (U.S.)",
	"Wallis and Futuna",
	"Western Sahara",
	"Yemen",
	"Zambia",
	"Zimbabwe",
];


const geCountryId = async (user) => {
  const [country] = await db.query(`SELECT id FROM countries WHERE name='${user.country}'`)
  const countryID = country[0].id
  return countryID
}

const getEmailType = async (user) => {
  const [email] = await db.query(`SELECT id FROM email_types WHERE e_type='${user.emailType}'`)
  const emailID = email[0].id
  return emailID
}

const getOwner = async (user) => {
  const [owner] = await db.query(`SELECT id FROM owners WHERE name='${user.owner}'`)
  const ownerID = owner[0].id
  return ownerID
}

// ///////////     inserting all:


const insertDummyData = async () => {
    
    let ownersINDB = await db.query(`SELECT * FROM owners`)
    let countriesINDB = await db.query(`SELECT * FROM countries`)
    let emailsINDB = await db.query(`SELECT * FROM email_types`)
    let clientsINDB = await db.query(`SELECT * FROM clients`)

    if(!ownersINDB){
        ////////////   inserting owners:
        
        const owners = {}
        clientsData.forEach( c => {
            if(!owners[c.owner]){
                owners[c.owner] = c.owner
            }
        })
        
        const ownersArr = Object.keys(owners)
        
        ownersArr.forEach(o => db.query(`INSERT INTO owners VALUES (null,'${o}')`))
    }

    if(!countriesINDB){
        //////////    inserting countries:

        countryList.forEach( async c => {
            await db.query(`INSERT INTO countries VALUES(null,"${c}");`)
          })

    if(!emailsINDB){
        
        /////////    inserting emailtypes :
        
        const emailTypes = ['A', 'B', 'C', 'D', 'null']
        
        emailTypes.forEach( e => db.query(`INSERT INTO email_types VALUES (null, '${e}');`) )
        
    }    

    if(!clientsINDB){
        clientsData.forEach( async c => {

            const ownerID = await getOwner(c)
            const emailID = await getEmailType(c)
            const countryID = await geCountryId(c)
            const date = dateFormat(c.firstContact,'isoDate')
            await db.query(`INSERT INTO clients VALUES(null, '${c.name}', '${date}', ${emailID}, ${c.sold}, ${ownerID}, ${countryID})`)
          })
          
    }

}        



// let conARR = [[2711,'Afghanistan'],
// 	[2721,'Albania'],
// 	[2731,'Algeria'],
// 	[2741,'American Samoa'],
// 	[2751,'Andorra'],
// 	[2761,'Angola'],
// 	[2771,'Anguilla'],
// 	[2781,'Antarctica'],
// 	[2791,'Antigua and Barbuda'],
// 	[2801,'Argentina'],
// 	[2811,'Armenia'],
// 	[2821,'Aruba'],
// 	[2831,'Australia'],
// 	[2841,'Austria'],
// 	[2851,'Azerbaijan'],
// 	[2861,'Bahamas'],
// 	[2871,'Bahrain'],
// 	[2881,'Bangladesh'],
// 	[2891,'Barbados'],
// 	[2901,'Belarus'],
// 	[2911,'Belgium'],
// 	[2921,'Belize'],
// 	[2931,'Benin'],
// 	[2941,'Bermuda'],
// 	[2951,'Bhutan'],
// 	[2961,'Bolivia'],
// 	[2971,'Bonaire, Sint Eustatius and Saba'],
// 	[2981,'Bosnia and Herzegovina'],
// 	[2991,'Botswana'],
// 	[3001,'Bouvet Island'],
// 	[3011,'Brazil'],
// 	[3021,'British Indian Ocean Territory'],
// 	[3031,'Brunei Darussalam'],
// 	[3041,'Bulgaria'],
// 	[3051,'Burkina Faso'],
// 	[3061,'Burundi'],
// 	[3071,'Cabo Verde'],
// 	[3081,'Cambodia'],
// 	[3091,'Cameroon'],
// 	[3101,'Canada'],
// 	[3111,'Cayman Islands'],
// 	[3121,'Central African Republic'],
// 	[3131,'Chad'],
// 	[3141,'Chile'],
// 	[3151,'China'],
// 	[3161,'Christmas Island'],
// 	[3171,'Cocos Islands'],
// 	[3181,'Colombia'],
// 	[3191,'Comoros'],
// 	[3201,'Congo'],
// 	[3211,'Congo'],
// 	[3221,'Cook Islands'],
// 	[3231,'Costa Rica'],
// 	[3241,'Croatia'],
// 	[3251,'Cuba'],
// 	[3261,'Curaçao'],
// 	[3271,'Cyprus'],
// 	[3281,'Czechia'],
// 	[3291,'Côte d\'Ivoire'],
// 	[3301,'Denmark'],
// 	[3311,'Djibouti'],
// 	[3321,'Dominica'],
// 	[3331,'Dominican Republic'],
// 	[3341,'Ecuador'],
// 	[3351,'Egypt'],
// 	[3361,'El Salvador'],
// 	[3371,'Equatorial Guinea'],
// 	[3381,'Eritrea'],
// 	[3391,'Estonia'],
// 	[3401,'Eswatini'],
// 	[3411,'Ethiopia'],
// 	[3421,'Falkland Islands'],
// 	[3431,'Faroe Islands'],
// 	[3441,'Fiji'],
// 	[3451,'Finland'],
// 	[3461,'France'],
// 	[3471,'French Guiana'],
// 	[3481,'French Polynesia'],
// 	[3491,'French Southern Territories'],
// 	[3501,'Gabon'],
// 	[3511,'Gambia'],
// 	[3521,'Georgia'],
// 	[3531,'Germany'],
// 	[3541,'Ghana'],
// 	[3551,'Gibraltar'],
// 	[3561,'Greece'],
// 	[3571,'Greenland'],
// 	[3581,'Grenada'],
// 	[3591,'Guadeloupe'],
// 	[3601,'Guam'],
// 	[3611,'Guatemala'],
// 	[3621,'Guernsey'],
// 	[3631,'Guinea'],
// 	[3641,'Guinea-Bissau'],
// 	[3651,'Guyana'],
// 	[3661,'Haiti'],
// 	[3671,'Heard Island and McDonald Islands'],
// 	[3681,'Holy See'],
// 	[3691,'Honduras'],
// 	[3701,'Hong Kong'],
// 	[3711,'Hungary'],
// 	[3721,'Iceland'],
// 	[3731,'India'],
// 	[3741,'Indonesia'],
// 	[3751,'Iran'],
// 	[3761,'Iraq'],
// 	[3771,'Ireland'],
// 	[3781,'Isle of Man'],
// 	[3791,'Israel'],
// 	[3801,'Italy'],
// 	[3811,'Jamaica'],
// 	[3821,'Japan'],
// 	[3831,'Jersey'],
// 	[3841,'Jordan'],
// 	[3851,'Kazakhstan'],
// 	[3861,'Kenya'],
// 	[3871,'Kiribati'],
// 	[3881,'Korea'],
// 	[3891,'Kuwait'],
// 	[3901,'Kyrgyzstan'],
// 	[3911,'Lao People\'s Democratic Republic'],
// 	[3921,'Latvia'],
// 	[3931,'Lebanon'],
// 	[3941,'Lesotho'],
// 	[3951,'Liberia'],
// 	[3961,'Libya'],
// 	[3971,'Liechtenstein'],
// 	[3981,'Lithuania'],
// 	[3991,'Luxembourg'],
// 	[4001,'Macao'],
// 	[4011,'Madagascar'],
// 	[4021,'Malawi'],
// 	[4031,'Malaysia'],
// 	[4041,'Maldives'],
// 	[4051,'Mali'],
// 	[4061,'Malta'],
// 	[4071,'Marshall Islands'],
// 	[4081,'Martinique'],
// 	[4091,'Mauritania'],
// 	[4101,'Mauritius'],
// 	[4111,'Mayotte'],
// 	[4121,'Mexico'],
// 	[4131,'Micronesia'],
// 	[4141,'Moldova'],
// 	[4151,'Monaco'],
// 	[4161,'Mongolia'],
// 	[4171,'Montenegro'],
// 	[4181,'Montserrat'],
// 	[4191,'Morocco'],
// 	[4201,'Mozambique'],
// 	[4211,'Myanmar'],
// 	[4221,'Namibia'],
// 	[4231,'Nauru'],
// 	[4241,'Nepal'],
// 	[4251,'Netherlands'],
// 	[4261,'New Caledonia'],
// 	[4271,'New Zealand'],
// 	[4281,'Nicaragua'],
// 	[4291,'Niger'],
// 	[4301,'Nigeria'],
// 	[4311,'Niue'],
// 	[4321,'Norfolk Island'],
// 	[4331,'Northern Mariana Islands'],
// 	[4341,'Norway'],
// 	[4351,'Oman'],
// 	[4361,'Pakistan'],
// 	[4371,'Palau'],
// 	[4381,'Panama'],
// 	[4391,'Papua New Guinea'],
// 	[4401,'Paraguay'],
// 	[4411,'Peru'],
// 	[4421,'Philippines'],
// 	[4431,'Pitcairn'],
// 	[4441,'Poland'],
// 	[4451,'Portugal'],
// 	[4461,'Puerto Rico'],
// 	[4471,'Qatar'],
// 	[4481,'Republic of North Macedonia'],
// 	[4491,'Romania'],
// 	[4501,'Russian Federation'],
// 	[4511,'Rwanda'],
// 	[4521,'Réunion'],
// 	[4531,'Saint Barthélemy'],
// 	[4541,'Saint Helena, Ascension and Tristan da C'],
// 	[4551,'Saint Kitts and Nevis'],
// 	[4561,'Saint Lucia'],
// 	[4571,'Saint Martin (French part)'],
// 	[4581,'Saint Pierre and Miquelon'],
// 	[4591,'Saint Vincent and the Grenadines'],
// 	[4601,'Samoa'],
// 	[4611,'San Marino'],
// 	[4621,'Sao Tome and Principe'],
// 	[4631,'Saudi Arabia'],
// 	[4641,'Senegal'],
// 	[4651,'Serbia'],
// 	[4661,'Seychelles'],
// 	[4671,'Sierra Leone'],
// 	[4681,'Singapore'],
// 	[4691,'Sint Maarten (Dutch part)'],
// 	[4701,'Slovakia'],
// 	[4711,'Slovenia'],
// 	[4721,'Solomon Islands'],
// 	[4731,'Somalia'],
// 	[4741,'South Africa'],
// 	[4751,'South Georgia and the South Sandwich Isl'],
// 	[4761,'South Sudan'],
// 	[4771,'Spain'],
// 	[4781,'Sri Lanka'],
// 	[4791,'Sudan'],
// 	[4801,'Suriname'],
// 	[4811,'Svalbard and Jan Mayen'],
// 	[4821,'Sweden'],
// 	[4831,'Switzerland'],
// 	[4841,'Syrian Arab Republic'],
// 	[4851,'Taiwan'],
// 	[4861,'Tajikistan'],
// 	[4871,'Tanzania'],
// 	[4881,'Thailand'],
// 	[4891,'Timor-Leste'],
// 	[4901,'Togo'],
// 	[4911,'Tokelau'],
// 	[4921,'Tonga'],
// 	[4931,'Trinidad and Tobago'],
// 	[4941,'Tunisia'],
// 	[4951,'Turkey'],
// 	[4961,'Turkmenistan'],
// 	[4971,'Turks and Caicos Islands'],
// 	[4981,'Tuvalu'],
// 	[4991,'Uganda'],
// 	[5001,'Ukraine'],
// 	[5011,'United Arab Emirates (UAE)'],
// 	[5021,'United Kingdom of Great Britain and Nort'],
// 	[5031,'United States of America (USA)'],
// 	[5041,'Uruguay'],
// 	[5051,'Uzbekistan'],
// 	[5061,'Vanuatu'],
// 	[5071,'Venezuela'],
// 	[5081,'Viet Nam'],
// 	[5091,'Virgin Islands (British)'],
// 	[5101,'Virgin Islands (U.S.)'],
// 	[5111,'Wallis and Futuna'],
// 	[5121,'Western Sahara'],
// 	[5131,'Yemen'],
// 	[5141,'Zambia'],
//     [5151,'Zimbabwe']]

//     conARR.forEach( c => {
//         db.query(`INSERT INTO countries VALUES(null,"${c}");`)
//       })